# Generated by Django 4.2.6 on 2023-12-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_campeonato', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_conquistados', models.IntegerField()),
                ('posicao_Equipe', models.IntegerField()),
                ('vitoria', models.IntegerField()),
                ('empate', models.IntegerField()),
                ('derrota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=100)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_partida', models.CharField(max_length=100)),
                ('times_partida', models.ManyToManyField(to='core.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_equipe', models.IntegerField()),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partida')),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_jogo', models.DateField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campeonato')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campus')),
                ('equipe', models.ManyToManyField(to='core.equipe')),
                ('resultado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.resultado')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('esporte', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campus')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='jogadores',
            field=models.ManyToManyField(to='core.jogador'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='tec_time',
            field=models.ManyToManyField(related_name='tecnico', to='core.jogador'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='campus_campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campus'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='equipes_campeonato',
            field=models.ManyToManyField(to='core.equipe'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='modalidade_campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modalidade'),
        ),
    ]
