# Generated by Django 4.2.6 on 2023-12-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='name',
            new_name='nome',
        ),
    ]
