# Generated by Django 4.2.6 on 2024-01-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='chaveamento_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torneio',
            name='esporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.esporte'),
        ),
    ]
