# Generated by Django 4.2.6 on 2023-12-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classificacaoequipe_esporte_historicoequipe_torneio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='esporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.esporte'),
        ),
    ]
