# Generated by Django 4.2.6 on 2023-12-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_campus_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='atuacao',
            field=models.CharField(choices=[('A', 'Atacante'), ('D', 'Defensor'), ('G', 'Goleiro'), ('T', 'Tecnico')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='tec_time',
            field=models.ManyToManyField(limit_choices_to={'atuacao': 'T'}, related_name='tecnico', to='core.jogador'),
        ),
    ]
