# Generated by Django 4.2.6 on 2024-01-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='campus',
        ),
    ]
