# Generated by Django 4.2.6 on 2023-12-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_jogador_esporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='placar_casa',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='placar_visitante',
        ),
        migrations.AddField(
            model_name='partida',
            name='placar',
            field=models.CharField(blank=True, default='0x0', max_length=50, null=True, verbose_name='Placar'),
        ),
    ]
