# Generated by Django 4.2.6 on 2023-12-12 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jogador_atuacao_alter_equipe_tec_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='campus_partida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.campus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jogador',
            name='esporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modalidade'),
        ),
    ]
