# Generated by Django 4.2.6 on 2024-01-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='torneio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='core.torneio'),
        ),
    ]
