# Generated by Django 4.2.6 on 2023-12-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_partida_placar_casa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='time1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_time1', to='core.equipe'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_time2', to='core.equipe'),
        ),
    ]
