# Generated by Django 4.2.6 on 2023-12-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='preferred_email',
        ),
    ]
