# Generated by Django 4.2.6 on 2023-12-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_partida_time1_alter_partida_time2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
    ]
