# Generated by Django 4.2.6 on 2023-12-27 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_changestudentteam_jogador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='jogadores',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
