# Generated by Django 4.2.6 on 2023-12-23 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_classificacaoequipe_historicoequipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='data',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.CreateModel(
            name='PartidaAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default='2023-01-01')),
                ('time1', models.CharField(max_length=100)),
                ('time2', models.CharField(max_length=100)),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.esporte')),
            ],
        ),
    ]
