# Generated by Django 4.2.6 on 2023-12-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_equipe_jogadores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changestudentteam',
            options={'verbose_name': 'Pedido de Transferência', 'verbose_name_plural': 'Pedidos de Transferência'},
        ),
        migrations.AlterField(
            model_name='equipe',
            name='jogadores',
            field=models.ManyToManyField(to='core.jogador'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
