# Generated by Django 4.2.6 on 2023-12-25 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_torneio_remove_partidaadd_esporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='esporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.esporte'),
        ),
    ]
