# Generated by Django 4.2.6 on 2023-12-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_partida_esporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='placar_casa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partida',
            name='placar_visitante',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time2',
            field=models.CharField(max_length=50),
        ),
    ]
