# Generated by Django 4.2.6 on 2023-12-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_partida_placar_casa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.torneio'),
        ),
    ]
